var PHRASES_DATA = [
  // ==================== Day 1 ====================
  [
    { phrase: 'break the ice', meaning: '打破僵局' },
    { phrase: 'make a living', meaning: '谋生' },
    { phrase: 'keep in touch', meaning: '保持联系' },
    { phrase: 'look forward to', meaning: '期待' },
    { phrase: 'get along with', meaning: '与...相处' },
    { phrase: 'make up one's mind', meaning: '下定决心' },
    { phrase: 'take it easy', meaning: '放松' },
    { phrase: 'come true', meaning: '实现' },
    { phrase: 'run out of', meaning: '用完' },
    { phrase: 'pay attention to', meaning: '注意' },
  ],
  // ==================== Day 2 ====================
  [
    { phrase: 'in addition to', meaning: '除...之外' },
    { phrase: 'as a result', meaning: '结果' },
    { phrase: 'on the other hand', meaning: '另一方面' },
    { phrase: 'in my opinion', meaning: '在我看来' },
    { phrase: 'to be honest', meaning: '老实说' },
    { phrase: 'as far as I know', meaning: '据我所知' },
    { phrase: 'in other words', meaning: '换句话说' },
    { phrase: 'on the contrary', meaning: '相反' },
    { phrase: 'for example', meaning: '例如' },
    { phrase: 'in conclusion', meaning: '总之' },
  ],
  // ==================== Day 3 ====================
  [
    { phrase: 'make a decision', meaning: '做决定' },
    { phrase: 'take advantage of', meaning: '利用' },
    { phrase: 'come up with', meaning: '想出' },
    { phrase: 'get rid of', meaning: '摆脱' },
    { phrase: 'put off', meaning: '推迟' },
    { phrase: 'turn out', meaning: '结果是' },
    { phrase: 'give up', meaning: '放弃' },
    { phrase: 'look up to', meaning: '尊敬' },
    { phrase: 'make use of', meaning: '利用' },
    { phrase: 'take care of', meaning: '照顾' },
  ],
  // ==================== Day 4 ====================
  [
    { phrase: 'be supposed to', meaning: '应该' },
    { phrase: 'used to', meaning: '过去常常' },
    { phrase: 'would rather', meaning: '宁愿' },
    { phrase: 'had better', meaning: '最好' },
    { phrase: 'be about to', meaning: '即将' },
    { phrase: 'be going to', meaning: '打算' },
    { phrase: 'be likely to', meaning: '可能' },
    { phrase: 'be able to', meaning: '能够' },
    { phrase: 'be willing to', meaning: '愿意' },
    { phrase: 'be afraid to', meaning: '害怕' },
  ],
  // ==================== Day 5 ====================
  [
    { phrase: 'in spite of', meaning: '尽管' },
    { phrase: 'due to', meaning: '由于' },
    { phrase: 'instead of', meaning: '代替' },
    { phrase: 'apart from', meaning: '除了' },
    { phrase: 'according to', meaning: '根据' },
    { phrase: 'thanks to', meaning: '多亏' },
    { phrase: 'except for', meaning: '除了' },
    { phrase: 'along with', meaning: '连同' },
    { phrase: 'as for', meaning: '至于' },
    { phrase: 'as to', meaning: '关于' },
  ],
  // ==================== Day 6 ====================
  [
    { phrase: 'make progress', meaning: '取得进步' },
    { phrase: 'do research', meaning: '做研究' },
    { phrase: 'take notes', meaning: '记笔记' },
    { phrase: 'hand in', meaning: '上交' },
    { phrase: 'go over', meaning: '复习' },
    { phrase: 'pick up', meaning: '捡起；学会' },
    { phrase: 'work out', meaning: '解决；锻炼' },
    { phrase: 'figure out', meaning: '弄清楚' },
    { phrase: 'carry out', meaning: '执行' },
    { phrase: 'find out', meaning: '发现' },
  ],
  // ==================== Day 7 ====================
  [
    { phrase: 'be engaged in', meaning: '从事' },
    { phrase: 'be responsible for', meaning: '负责' },
    { phrase: 'be familiar with', meaning: '熟悉' },
    { phrase: 'be interested in', meaning: '对...感兴趣' },
    { phrase: 'be satisfied with', meaning: '对...满意' },
    { phrase: 'be proud of', meaning: '为...骄傲' },
    { phrase: 'be worried about', meaning: '担心' },
    { phrase: 'be concerned about', meaning: '关心' },
    { phrase: 'be aware of', meaning: '意识到' },
    { phrase: 'be fond of', meaning: '喜欢' },
  ],
  // ==================== Day 8 ====================
  [
    { phrase: 'in the long run', meaning: '从长远看' },
    { phrase: 'in the short term', meaning: '短期' },
    { phrase: 'at the moment', meaning: '此刻' },
    { phrase: 'in the future', meaning: '将来' },
    { phrase: 'from now on', meaning: '从现在起' },
    { phrase: 'sooner or later', meaning: '迟早' },
    { phrase: 'all of a sudden', meaning: '突然' },
    { phrase: 'once upon a time', meaning: '从前' },
    { phrase: 'in the end', meaning: '最终' },
    { phrase: 'at last', meaning: '最后' },
  ],
  // ==================== Day 9 ====================
  [
    { phrase: 'make a difference', meaning: '有影响' },
    { phrase: 'make a contribution to', meaning: '贡献' },
    { phrase: 'make an effort', meaning: '努力' },
    { phrase: 'make a mistake', meaning: '犯错' },
    { phrase: 'make a promise', meaning: '承诺' },
    { phrase: 'make a plan', meaning: '制定计划' },
    { phrase: 'make a choice', meaning: '做选择' },
    { phrase: 'make friends', meaning: '交朋友' },
    { phrase: 'make money', meaning: '赚钱' },
    { phrase: 'make sense', meaning: '有道理' },
  ],
  // ==================== Day 10 ====================
  [
    { phrase: 'take part in', meaning: '参加' },
    { phrase: 'take place', meaning: '发生' },
    { phrase: 'take effect', meaning: '生效' },
    { phrase: 'take action', meaning: '采取行动' },
    { phrase: 'take responsibility', meaning: '承担责任' },
    { phrase: 'take measures', meaning: '采取措施' },
    { phrase: 'take steps', meaning: '采取措施' },
    { phrase: 'take risks', meaning: '冒险' },
    { phrase: 'take chances', meaning: '抓住机会' },
    { phrase: 'take time', meaning: '花时间' },
  ],
  // ==================== Day 11 ====================
  [
    { phrase: 'fall in love', meaning: '恋爱' },
    { phrase: 'break up', meaning: '分手' },
    { phrase: 'get married', meaning: '结婚' },
    { phrase: 'settle down', meaning: '安定' },
    { phrase: 'grow up', meaning: '长大' },
    { phrase: 'turn around', meaning: '转身' },
    { phrase: 'calm down', meaning: '冷静' },
    { phrase: 'cheer up', meaning: '振作' },
    { phrase: 'give in', meaning: '屈服' },
    { phrase: 'hold on', meaning: '坚持' },
  ],
  // ==================== Day 12 ====================
  [
    { phrase: 'at heart', meaning: '本质上' },
    { phrase: 'in mind', meaning: '在脑海中' },
    { phrase: 'on purpose', meaning: '故意' },
    { phrase: 'by accident', meaning: '偶然' },
    { phrase: 'in fact', meaning: '事实上' },
    { phrase: 'at least', meaning: '至少' },
    { phrase: 'at most', meaning: '至多' },
    { phrase: 'in general', meaning: '总的来说' },
    { phrase: 'on average', meaning: '平均' },
    { phrase: 'by chance', meaning: '碰巧' },
  ],
  // ==================== Day 13 ====================
  [
    { phrase: 'have an impact on', meaning: '对...有影响' },
    { phrase: 'have an effect on', meaning: '对...有影响' },
    { phrase: 'have influence on', meaning: '对...有影响' },
    { phrase: 'have access to', meaning: '能使用' },
    { phrase: 'have control over', meaning: '控制' },
    { phrase: 'have confidence in', meaning: '对...有信心' },
    { phrase: 'have faith in', meaning: '信任' },
    { phrase: 'have trouble with', meaning: '在...有困难' },
    { phrase: 'have difficulty with', meaning: '在...有困难' },
    { phrase: 'have a good time', meaning: '玩得开心' },
  ],
  // ==================== Day 14 ====================
  [
    { phrase: 'look after', meaning: '照顾' },
    { phrase: 'look for', meaning: '寻找' },
    { phrase: 'look into', meaning: '调查' },
    { phrase: 'look through', meaning: '浏览' },
    { phrase: 'look over', meaning: '检查' },
    { phrase: 'look up', meaning: '查找' },
    { phrase: 'look down on', meaning: '看不起' },
    { phrase: 'look back on', meaning: '回顾' },
    { phrase: 'look around', meaning: '环顾' },
    { phrase: 'look out', meaning: '小心' },
  ],
  // ==================== Day 15 ====================
  [
    { phrase: 'turn on', meaning: '打开' },
    { phrase: 'turn off', meaning: '关闭' },
    { phrase: 'turn up', meaning: '出现；调大' },
    { phrase: 'turn down', meaning: '拒绝；调小' },
    { phrase: 'turn to', meaning: '求助于' },
    { phrase: 'turn into', meaning: '变成' },
    { phrase: 'turn over', meaning: '翻转' },
    { phrase: 'turn away', meaning: '转身离开' },
    { phrase: 'turn back', meaning: '返回' },
    { phrase: 'turn out', meaning: '结果是' },
  ],
  // ==================== Day 16 ====================
  [
    { phrase: 'in terms of', meaning: '就...而言' },
    { phrase: 'with regard to', meaning: '关于' },
    { phrase: 'in relation to', meaning: '关于' },
    { phrase: 'as opposed to', meaning: '而不是' },
    { phrase: 'in contrast to', meaning: '与...对比' },
    { phrase: 'compared with', meaning: '与...相比' },
    { phrase: 'different from', meaning: '与...不同' },
    { phrase: 'similar to', meaning: '与...相似' },
    { phrase: 'the same as', meaning: '与...相同' },
    { phrase: 'equivalent to', meaning: '等同于' },
  ],
  // ==================== Day 17 ====================
  [
    { phrase: 'point out', meaning: '指出' },
    { phrase: 'bring up', meaning: '提出；抚养' },
    { phrase: 'bring about', meaning: '引起' },
    { phrase: 'bring out', meaning: '出版；显现' },
    { phrase: 'bring in', meaning: '引入' },
    { phrase: 'carry on', meaning: '继续' },
    { phrase: 'carry out', meaning: '执行' },
    { phrase: 'carry away', meaning: '带走' },
    { phrase: 'carry forward', meaning: '发扬' },
    { phrase: 'carry on', meaning: '继续' },
  ],
  // ==================== Day 18 ====================
  [
    { phrase: 'account for', meaning: '解释；占' },
    { phrase: 'allow for', meaning: '考虑到' },
    { phrase: 'apply for', meaning: '申请' },
    { phrase: 'arrange for', meaning: '安排' },
    { phrase: 'ask for', meaning: '请求' },
    { phrase: 'call for', meaning: '需要' },
    { phrase: 'care for', meaning: '关心' },
    { phrase: 'check for', meaning: '检查' },
    { phrase: 'compensate for', meaning: '补偿' },
    { phrase: 'provide for', meaning: '供养' },
  ],
  // ==================== Day 19 ====================
  [
    { phrase: 'come across', meaning: '偶遇' },
    { phrase: 'come along', meaning: '进展' },
    { phrase: 'come about', meaning: '发生' },
    { phrase: 'come down to', meaning: '归结为' },
    { phrase: 'come up with', meaning: '想出' },
    { phrase: 'come into effect', meaning: '生效' },
    { phrase: 'come into being', meaning: '形成' },
    { phrase: 'come to an end', meaning: '结束' },
    { phrase: 'come to terms', meaning: '妥协' },
    { phrase: 'come to life', meaning: '活跃起来' },
  ],
  // ==================== Day 20 ====================
  [
    { phrase: 'go through', meaning: '经历' },
    { phrase: 'go over', meaning: '复习' },
    { phrase: 'go ahead', meaning: '前进' },
    { phrase: 'go by', meaning: '经过' },
    { phrase: 'go down', meaning: '下降' },
    { phrase: 'go up', meaning: '上升' },
    { phrase: 'go off', meaning: '离开；爆炸' },
    { phrase: 'go on', meaning: '继续' },
    { phrase: 'go out', meaning: '出去' },
    { phrase: 'go with', meaning: '与...相配' },
  ],
];