var VOCAB_LIST = [
  // ==================== Day 1 (1-40) ====================
  { word: 'abandon', phonetic: '/əˈbændən/', meaning: 'v. 放弃；抛弃', example: 'He abandoned his car on the highway.', exampleZh: '他把车扔在了高速公路上。', pos: 'v.', level: 'core' },
  { word: 'ability', phonetic: '/əˈbɪləti/', meaning: 'n. 能力；才能', example: 'She has the ability to solve problems.', exampleZh: '她有解决问题的能力。', pos: 'n.', level: 'core' },
  { word: 'able', phonetic: '/ˈeɪbl/', meaning: 'adj. 能干的；有能力的', example: 'He is able to swim across the river.', exampleZh: '他能游过这条河。', pos: 'adj.', level: 'core' },
  { word: 'about', phonetic: '/əˈbaʊt/', meaning: 'prep. 关于；大约', example: 'They talked about the plan.', exampleZh: '他们讨论了那个计划。', pos: 'prep.', level: 'core' },
  { word: 'above', phonetic: '/əˈbʌv/', meaning: 'prep. 在……上方', example: 'The plane flew above the clouds.', exampleZh: '飞机飞越了云层。', pos: 'prep.', level: 'core' },
  { word: 'accept', phonetic: '/əkˈsept/', meaning: 'v. 接受；同意', example: 'I accept your apology.', exampleZh: '我接受你的道歉。', pos: 'v.', level: 'core' },
  { word: 'access', phonetic: '/ˈækses/', meaning: 'n. 进入；通道；访问', example: 'Students have access to the library.', exampleZh: '学生可以使用图书馆。', pos: 'n.', level: 'core' },
  { word: 'accident', phonetic: '/ˈæksɪdənt/', meaning: 'n. 事故；意外', example: 'A car accident happened yesterday.', exampleZh: '昨天发生了一起车祸。', pos: 'n.', level: 'core' },
  { word: 'account', phonetic: '/əˈkaʊnt/', meaning: 'n. 账户；描述', example: 'He opened a bank account.', exampleZh: '他开了一个银行账户。', pos: 'n.', level: 'core' },
  { word: 'achieve', phonetic: '/əˈtʃiːv/', meaning: 'v. 实现；达到', example: 'She achieved her goal.', exampleZh: '她实现了她的目标。', pos: 'v.', level: 'core' },
  { word: 'across', phonetic: '/əˈkrɒs/', meaning: 'prep. 穿过；横过', example: 'He walked across the street.', exampleZh: '他穿过了街道。', pos: 'prep.', level: 'core' },
  { word: 'act', phonetic: '/ækt/', meaning: 'v. 行动；表演 n. 行为', example: 'We must act now.', exampleZh: '我们必须现在行动。', pos: 'v.', level: 'core' },
  { word: 'action', phonetic: '/ˈækʃn/', meaning: 'n. 行动；行为', example: 'Actions speak louder than words.', exampleZh: '行动胜于言辞。', pos: 'n.', level: 'core' },
  { word: 'active', phonetic: '/ˈæktɪv/', meaning: 'adj. 活跃的；积极的', example: 'She is an active member of the club.', exampleZh: '她是俱乐部的积极成员。', pos: 'adj.', level: 'core' },
  { word: 'activity', phonetic: '/ækˈtɪvəti/', meaning: 'n. 活动', example: 'Reading is my favorite activity.', exampleZh: '阅读是我最喜欢的活动。', pos: 'n.', level: 'core' },
  { word: 'actual', phonetic: '/ˈæktʃuəl/', meaning: 'adj. 实际的；真实的', example: 'The actual cost was higher.', exampleZh: '实际成本更高。', pos: 'adj.', level: 'core' },
  { word: 'add', phonetic: '/æd/', meaning: 'v. 增加；添加', example: 'Please add some sugar.', exampleZh: '请加些糖。', pos: 'v.', level: 'core' },
  { word: 'address', phonetic: '/əˈdres/', meaning: 'n. 地址 v. 解决', example: 'What is your home address?', exampleZh: '你家的地址是什么？', pos: 'n.', level: 'core' },
  { word: 'admit', phonetic: '/ədˈmɪt/', meaning: 'v. 承认；准许进入', example: 'He admitted his mistake.', exampleZh: '他承认了自己的错误。', pos: 'v.', level: 'core' },
  { word: 'adult', phonetic: '/ˈædʌlt/', meaning: 'n. 成年人', example: 'This movie is for adults only.', exampleZh: '这部电影仅限成人观看。', pos: 'n.', level: 'core' },
  { word: 'advance', phonetic: '/ədˈvɑːns/', meaning: 'n. 进步 v. 前进', example: 'Technology advances rapidly.', exampleZh: '科技发展迅速。', pos: 'v.', level: 'core' },
  { word: 'advantage', phonetic: '/ədˈvɑːntɪdʒ/', meaning: 'n. 优势；有利条件', example: 'Knowing English is a great advantage.', exampleZh: '懂英语是一大优势。', pos: 'n.', level: 'core' },
  { word: 'adventure', phonetic: '/ədˈventʃə/', meaning: 'n. 冒险；奇遇', example: 'The trip was a big adventure.', exampleZh: '这次旅行是一次大冒险。', pos: 'n.', level: 'core' },
  { word: 'advice', phonetic: '/ədˈvaɪs/', meaning: 'n. 建议；忠告', example: 'She gave me good advice.', exampleZh: '她给了我很好的建议。', pos: 'n.', level: 'core' },
  { word: 'advise', phonetic: '/ədˈvaɪz/', meaning: 'v. 建议；劝告', example: 'I advise you to study hard.', exampleZh: '我建议你努力学习。', pos: 'v.', level: 'core' },
  { word: 'affect', phonetic: '/əˈfekt/', meaning: 'v. 影响；感动', example: 'The weather affects our mood.', exampleZh: '天气影响我们的心情。', pos: 'v.', level: 'core' },
  { word: 'afford', phonetic: '/əˈfɔːd/', meaning: 'v. 买得起；负担得起', example: 'I cannot afford a new car.', exampleZh: '我买不起新车。', pos: 'v.', level: 'core' },
  { word: 'afraid', phonetic: '/əˈfreɪd/', meaning: 'adj. 害怕的；担心的', example: 'She is afraid of dogs.', exampleZh: '她害怕狗。', pos: 'adj.', level: 'core' },
  { word: 'after', phonetic: '/ˈɑːftə/', meaning: 'prep. 在……之后', example: 'I will call you after lunch.', exampleZh: '午饭后我会给你打电话。', pos: 'prep.', level: 'core' },
  { word: 'afternoon', phonetic: '/ˌɑːftəˈnuːn/', meaning: 'n. 下午', example: 'We met in the afternoon.', exampleZh: '我们下午见了面。', pos: 'n.', level: 'core' },
  { word: 'again', phonetic: '/əˈɡen/', meaning: 'adv. 又；再', example: 'Please say it again.', exampleZh: '请再说一遍。', pos: 'adv.', level: 'core' },
  { word: 'against', phonetic: '/əˈɡenst/', meaning: 'prep. 反对；对着', example: 'He leaned against the wall.', exampleZh: '他靠在墙上。', pos: 'prep.', level: 'core' },
  { word: 'age', phonetic: '/eɪdʒ/', meaning: 'n. 年龄', example: 'What is your age?', exampleZh: '你多大了？', pos: 'n.', level: 'core' },
  { word: 'agency', phonetic: '/ˈeɪdʒənsi/', meaning: 'n. 代理处；机构', example: 'She works at a travel agency.', exampleZh: '她在旅行社工作。', pos: 'n.', level: 'core' },
  { word: 'agent', phonetic: '/ˈeɪdʒənt/', meaning: 'n. 代理人；特工', example: 'The agent sold the house quickly.', exampleZh: '代理人很快卖出了房子。', pos: 'n.', level: 'core' },
  { word: 'ago', phonetic: '/əˈɡəʊ/', meaning: 'adv. 以前', example: 'He left two days ago.', exampleZh: '他两天前离开了。', pos: 'adv.', level: 'core' },
  { word: 'agree', phonetic: '/əˈɡriː/', meaning: 'v. 同意；赞成', example: 'I agree with you.', exampleZh: '我同意你的看法。', pos: 'v.', level: 'core' },
  { word: 'aim', phonetic: '/eɪm/', meaning: 'n. 目标 v. 瞄准', example: 'My aim is to pass the exam.', exampleZh: '我的目标是通过考试。', pos: 'n.', level: 'core' },
  { word: 'air', phonetic: '/eə/', meaning: 'n. 空气；空中', example: 'Open the window for fresh air.', exampleZh: '打开窗户透透气。', pos: 'n.', level: 'core' },
  { word: 'all', phonetic: '/ɔːl/', meaning: 'adj. 全部的 pron. 一切', example: 'All students passed the exam.', exampleZh: '所有学生都通过了考试。', pos: 'adj.', level: 'core' },

  // ==================== Day 2 (41-80) ====================
  { word: 'allow', phonetic: '/əˈlaʊ/', meaning: 'v. 允许；许可', example: 'Smoking is not allowed here.', exampleZh: '这里不允许吸烟。', pos: 'v.', level: 'core' },
  { word: 'almost', phonetic: '/ˈɔːlməʊst/', meaning: 'adv. 几乎；差不多', example: 'It is almost finished.', exampleZh: '差不多完成了。', pos: 'adv.', level: 'core' },
  { word: 'alone', phonetic: '/əˈləʊn/', meaning: 'adj. 单独的 adv. 独自', example: 'She lives alone.', exampleZh: '她独自居住。', pos: 'adj.', level: 'core' },
  { word: 'along', phonetic: '/əˈlɒŋ/', meaning: 'prep. 沿着', example: 'We walked along the river.', exampleZh: '我们沿着河边走。', pos: 'prep.', level: 'core' },
  { word: 'already', phonetic: '/ɔːlˈredi/', meaning: 'adv. 已经', example: 'He has already left.', exampleZh: '他已经离开了。', pos: 'adv.', level: 'core' },
  { word: 'also', phonetic: '/ˈɔːlsəʊ/', meaning: 'adv. 也；同样', example: 'She also speaks French.', exampleZh: '她也会说法语。', pos: 'adv.', level: 'core' },
  { word: 'although', phonetic: '/ɔːlˈðəʊ/', meaning: 'conj. 虽然；尽管', example: 'Although it rained, we went out.', exampleZh: '虽然下雨了，我们还是出去了。', pos: 'conj.', level: 'core' },
  { word: 'always', phonetic: '/ˈɔːlweɪz/', meaning: 'adv. 总是；一直', example: 'He is always late.', exampleZh: '他总是迟到。', pos: 'adv.', level: 'core' },
  { word: 'among', phonetic: '/əˈmʌŋ/', meaning: 'prep. 在……之中', example: 'She is popular among her friends.', exampleZh: '她在朋友中很受欢迎。', pos: 'prep.', level: 'core' },
  { word: 'amount', phonetic: '/əˈmaʊnt/', meaning: 'n. 数量；总额', example: 'A large amount of money was lost.', exampleZh: '丢失了大量金钱。', pos: 'n.', level: 'core' },
  { word: 'analyze', phonetic: '/ˈænəlaɪz/', meaning: 'v. 分析', example: 'We need to analyze the data.', exampleZh: '我们需要分析数据。', pos: 'v.', level: 'core' },
  { word: 'ancient', phonetic: '/ˈeɪnʃənt/', meaning: 'adj. 古老的；古代的', example: 'They visited an ancient temple.', exampleZh: '他们参观了一座古老的寺庙。', pos: 'adj.', level: 'core' },
  { word: 'anger', phonetic: '/ˈæŋɡə/', meaning: 'n. 愤怒', example: 'He spoke with anger.', exampleZh: '他愤怒地说。', pos: 'n.', level: 'core' },
  { word: 'angle', phonetic: '/ˈæŋɡl/', meaning: 'n. 角度；观点', example: 'Look at it from a different angle.', exampleZh: '从不同的角度看这件事。', pos: 'n.', level: 'core' },
  { word: 'angry', phonetic: '/ˈæŋɡri/', meaning: 'adj. 生气的；愤怒的', example: 'She was angry at him.', exampleZh: '她生他的气。', pos: 'adj.', level: 'core' },
  { word: 'animal', phonetic: '/ˈænɪml/', meaning: 'n. 动物', example: 'Dogs are loyal animals.', exampleZh: '狗是忠诚的动物。', pos: 'n.', level: 'core' },
  { word: 'announce', phonetic: '/əˈnaʊns/', meaning: 'v. 宣布；通知', example: 'They announced the results.', exampleZh: '他们宣布了结果。', pos: 'v.', level: 'core' },
  { word: 'annual', phonetic: '/ˈænjuəl/', meaning: 'adj. 每年的；年度的', example: 'This is our annual meeting.', exampleZh: '这是我们的年度会议。', pos: 'adj.', level: 'core' },
  { word: 'another', phonetic: '/əˈnʌðə/', meaning: 'adj. 另一个', example: 'Would you like another cup?', exampleZh: '你想再来一杯吗？', pos: 'adj.', level: 'core' },
  { word: 'answer', phonetic: '/ˈɑːnsə/', meaning: 'n. 答案 v. 回答', example: 'Please answer the question.', exampleZh: '请回答这个问题。', pos: 'v.', level: 'core' },
  { word: 'anxious', phonetic: '/ˈæŋkʃəs/', meaning: 'adj. 焦虑的；担心的', example: 'She felt anxious about the test.', exampleZh: '她对考试感到焦虑。', pos: 'adj.', level: 'core' },
  { word: 'any', phonetic: '/ˈeni/', meaning: 'adj. 任何的', example: 'Do you have any questions?', exampleZh: '你有什么问题吗？', pos: 'adj.', level: 'core' },
  { word: 'anyone', phonetic: '/ˈeniwʌn/', meaning: 'pron. 任何人', example: 'Is anyone here?', exampleZh: '有人在吗？', pos: 'pron.', level: 'core' },
  { word: 'anything', phonetic: '/ˈeniθɪŋ/', meaning: 'pron. 任何事', example: 'Did you say anything?', exampleZh: '你说了什么吗？', pos: 'pron.', level: 'core' },
  { word: 'apart', phonetic: '/əˈpɑːt/', meaning: 'adv. 分开；分离', example: 'They live apart.', exampleZh: '他们分居了。', pos: 'adv.', level: 'core' },
  { word: 'appear', phonetic: '/əˈpɪə/', meaning: 'v. 出现；似乎', example: 'He appeared at the door.', exampleZh: '他出现在门口。', pos: 'v.', level: 'core' },
  { word: 'apply', phonetic: '/əˈplaɪ/', meaning: 'v. 申请；应用', example: 'She applied for the job.', exampleZh: '她申请了那份工作。', pos: 'v.', level: 'core' },
  { word: 'appoint', phonetic: '/əˈpɔɪnt/', meaning: 'v. 任命；指定', example: 'He was appointed manager.', exampleZh: '他被任命为经理。', pos: 'v.', level: 'core' },
  { word: 'approach', phonetic: '/əˈprəʊtʃ/', meaning: 'v. 接近 n. 方法', example: 'We need a new approach.', exampleZh: '我们需要一个新方法。', pos: 'n.', level: 'core' },
  { word: 'appropriate', phonetic: '/əˈprəʊpriət/', meaning: 'adj. 适当的；合适的', example: 'Wear appropriate clothes.', exampleZh: '穿合适的衣服。', pos: 'adj.', level: 'core' },
  { word: 'approve', phonetic: '/əˈpruːv/', meaning: 'v. 批准；赞成', example: 'The plan was approved.', exampleZh: '计划被批准了。', pos: 'v.', level: 'core' },
  { word: 'area', phonetic: '/ˈeəriə/', meaning: 'n. 区域；面积', example: 'This area is very safe.', exampleZh: '这个区域很安全。', pos: 'n.', level: 'core' },
  { word: 'argue', phonetic: '/ˈɑːɡjuː/', meaning: 'v. 争论；辩论', example: 'They argue about money.', exampleZh: '他们为钱争吵。', pos: 'v.', level: 'core' },
  { word: 'arise', phonetic: '/əˈraɪz/', meaning: 'v. 出现；产生', example: 'Problems may arise.', exampleZh: '可能会出现问题。', pos: 'v.', level: 'core' },
  { word: 'arm', phonetic: '/ɑːm/', meaning: 'n. 手臂 v. 武装', example: 'He broke his arm.', exampleZh: '他摔断了手臂。', pos: 'n.', level: 'core' },
  { word: 'army', phonetic: '/ˈɑːmi/', meaning: 'n. 军队', example: 'He joined the army.', exampleZh: '他参军了。', pos: 'n.', level: 'core' },
  { word: 'around', phonetic: '/əˈraʊnd/', meaning: 'prep. 在……周围', example: 'They sat around the table.', exampleZh: '他们围坐在桌旁。', pos: 'prep.', level: 'core' },
  { word: 'arrange', phonetic: '/əˈreɪndʒ/', meaning: 'v. 安排；排列', example: 'I will arrange the meeting.', exampleZh: '我来安排会议。', pos: 'v.', level: 'core' },
  { word: 'arrive', phonetic: '/əˈraɪv/', meaning: 'v. 到达', example: 'We arrived at the station.', exampleZh: '我们到达了车站。', pos: 'v.', level: 'core' },
  { word: 'art', phonetic: '/ɑːt/', meaning: 'n. 艺术；美术', example: 'She loves modern art.', exampleZh: '她喜欢现代艺术。', pos: 'n.', level: 'core' },
  { word: 'article', phonetic: '/ˈɑːtɪkl/', meaning: 'n. 文章；物品', example: 'I read an interesting article.', exampleZh: '我读了一篇有趣的文章。', pos: 'n.', level: 'core' },

  // ==================== Day 3 (81-120) ====================
  { word: 'ask', phonetic: '/ɑːsk/', meaning: 'v. 问；要求', example: 'May I ask a question?', exampleZh: '我可以问个问题吗？', pos: 'v.', level: 'core' },
  { word: 'assist', phonetic: '/əˈsɪst/', meaning: 'v. 协助；帮助', example: 'He assisted me with the work.', exampleZh: '他协助我完成工作。', pos: 'v.', level: 'core' },
  { word: 'assume', phonetic: '/əˈsjuːm/', meaning: 'v. 假定；设想', example: 'I assume you are right.', exampleZh: '我假设你是对的。', pos: 'v.', level: 'core' },
  { word: 'attach', phonetic: '/əˈtætʃ/', meaning: 'v. 附加；附着', example: 'Please attach the file.', exampleZh: '请附上文件。', pos: 'v.', level: 'core' },
  { word: 'attack', phonetic: '/əˈtæk/', meaning: 'v. 攻击 n. 攻击', example: 'The dog attacked the cat.', exampleZh: '狗攻击了猫。', pos: 'v.', level: 'core' },
  { word: 'attempt', phonetic: '/əˈtempt/', meaning: 'v. 尝试 n. 企图', example: 'He attempted to escape.', exampleZh: '他企图逃跑。', pos: 'v.', level: 'core' },
  { word: 'attend', phonetic: '/əˈtend/', meaning: 'v. 出席；参加', example: 'She attended the wedding.', exampleZh: '她参加了婚礼。', pos: 'v.', level: 'core' },
  { word: 'attention', phonetic: '/əˈtenʃn/', meaning: 'n. 注意；关心', example: 'Pay attention to the teacher.', exampleZh: '注意听老师讲。', pos: 'n.', level: 'core' },
  { word: 'attitude', phonetic: '/ˈætɪtjuːd/', meaning: 'n. 态度；看法', example: 'His attitude is positive.', exampleZh: '他的态度很积极。', pos: 'n.', level: 'core' },
  { word: 'attract', phonetic: '/əˈtrækt/', meaning: 'v. 吸引', example: 'The show attracts many people.', exampleZh: '演出吸引了很多人。', pos: 'v.', level: 'core' },
  { word: 'audience', phonetic: '/ˈɔːdiəns/', meaning: 'n. 观众；听众', example: 'The audience clapped loudly.', exampleZh: '观众大声鼓掌。', pos: 'n.', level: 'core' },
  { word: 'author', phonetic: '/ˈɔːθə/', meaning: 'n. 作者；作家', example: 'Who is the author of this book?', exampleZh: '这本书的作者是谁？', pos: 'n.', level: 'core' },
  { word: 'available', phonetic: '/əˈveɪləbl/', meaning: 'adj. 可用的；可获得的', example: 'Is this seat available?', exampleZh: '这个座位有人吗？', pos: 'adj.', level: 'core' },
  { word: 'average', phonetic: '/ˈævərɪdʒ/', meaning: 'adj. 平均的 n. 平均', example: 'The average score was 80.', exampleZh: '平均分是80分。', pos: 'adj.', level: 'core' },
  { word: 'avoid', phonetic: '/əˈvɔɪd/', meaning: 'v. 避免；躲开', example: 'Avoid eating too much sugar.', exampleZh: '避免吃太多糖。', pos: 'v.', level: 'core' },
  { word: 'award', phonetic: '/əˈwɔːd/', meaning: 'n. 奖品 v. 授予', example: 'She won an award.', exampleZh: '她获得了一个奖项。', pos: 'n.', level: 'core' },
  { word: 'aware', phonetic: '/əˈweə/', meaning: 'adj. 意识到的；知道的', example: 'Are you aware of the risk?', exampleZh: '你意识到风险了吗？', pos: 'adj.', level: 'core' },
  { word: 'away', phonetic: '/əˈweɪ/', meaning: 'adv. 离开；远离', example: 'Please go away.', exampleZh: '请走开。', pos: 'adv.', level: 'core' },
  { word: 'baby', phonetic: '/ˈbeɪbi/', meaning: 'n. 婴儿', example: 'The baby is sleeping.', exampleZh: '婴儿在睡觉。', pos: 'n.', level: 'core' },
  { word: 'back', phonetic: '/bæk/', meaning: 'n. 背部 adv. 回来', example: 'He came back home.', exampleZh: '他回家了。', pos: 'adv.', level: 'core' },
  { word: 'background', phonetic: '/ˈbækɡraʊnd/', meaning: 'n. 背景', example: 'Tell me about your background.', exampleZh: '告诉我你的背景。', pos: 'n.', level: 'core' },
  { word: 'bad', phonetic: '/bæd/', meaning: 'adj. 坏的；糟糕的', example: 'The weather is bad today.', exampleZh: '今天天气不好。', pos: 'adj.', level: 'core' },
  { word: 'bag', phonetic: '/bæɡ/', meaning: 'n. 包；袋子', example: 'She put the book in her bag.', exampleZh: '她把书放进包里。', pos: 'n.', level: 'core' },
  { word: 'balance', phonetic: '/ˈbæləns/', meaning: 'n. 平衡 v. 平衡', example: 'Keep a balance in life.', exampleZh: '保持生活平衡。', pos: 'n.', level: 'core' },
  { word: 'ball', phonetic: '/bɔːl/', meaning: 'n. 球；舞会', example: 'The boy kicked the ball.', exampleZh: '男孩踢了球。', pos: 'n.', level: 'core' },
  { word: 'bank', phonetic: '/bæŋk/', meaning: 'n. 银行；河岸', example: 'I need to go to the bank.', exampleZh: '我需要去银行。', pos: 'n.', level: 'core' },
  { word: 'base', phonetic: '/beɪs/', meaning: 'n. 基础 v. 以……为基础', example: 'Trust is the base of friendship.', exampleZh: '信任是友谊的基础。', pos: 'n.', level: 'core' },
  { word: 'basic', phonetic: '/ˈbeɪsɪk/', meaning: 'adj. 基本的；基础的', example: 'These are basic skills.', exampleZh: '这些是基本技能。', pos: 'adj.', level: 'core' },
  { word: 'basis', phonetic: '/ˈbeɪsɪs/', meaning: 'n. 基础；根据', example: 'On what basis did you decide?', exampleZh: '你根据什么做的决定？', pos: 'n.', level: 'core' },
  { word: 'bath', phonetic: '/bɑːθ/', meaning: 'n. 洗澡', example: 'He takes a bath every day.', exampleZh: '他每天洗澡。', pos: 'n.', level: 'core' },
  { word: 'battle', phonetic: '/ˈbætl/', meaning: 'n. 战斗 v. 战斗', example: 'They won the battle.', exampleZh: '他们赢得了战斗。', pos: 'n.', level: 'core' },
  { word: 'beach', phonetic: '/biːtʃ/', meaning: 'n. 海滩', example: 'We walked on the beach.', exampleZh: '我们在海滩上散步。', pos: 'n.', level: 'core' },
  { word: 'bear', phonetic: '/beə/', meaning: 'v. 承受；忍受 n. 熊', example: 'I cannot bear the pain.', exampleZh: '我无法忍受这种痛苦。', pos: 'v.', level: 'core' },
  { word: 'beat', phonetic: '/biːt/', meaning: 'v. 打败；敲打', example: 'Our team beat theirs.', exampleZh: '我们队打败了他们。', pos: 'v.', level: 'core' },
  { word: 'beautiful', phonetic: '/ˈbjuːtɪfl/', meaning: 'adj. 美丽的', example: 'What a beautiful flower!', exampleZh: '多美的花啊！', pos: 'adj.', level: 'core' },
  { word: 'because', phonetic: '/bɪˈkɒz/', meaning: 'conj. 因为', example: 'I am happy because you came.', exampleZh: '我很高兴因为你来了。', pos: 'conj.', level: 'core' },
  { word: 'become', phonetic: '/bɪˈkʌm/', meaning: 'v. 变成；成为', example: 'She became a doctor.', exampleZh: '她成了一名医生。', pos: 'v.', level: 'core' },
  { word: 'before', phonetic: '/bɪˈfɔː/', meaning: 'prep. 在……之前', example: 'Wash your hands before dinner.', exampleZh: '饭前洗手。', pos: 'prep.', level: 'core' },
  { word: 'begin', phonetic: '/bɪˈɡɪn/', meaning: 'v. 开始', example: 'The class begins at eight.', exampleZh: '课八点开始。', pos: 'v.', level: 'core' },
  { word: 'behind', phonetic: '/bɪˈhaɪnd/', meaning: 'prep. 在……后面', example: 'The cat is behind the door.', exampleZh: '猫在门后面。', pos: 'prep.', level: 'core' },
  { word: 'believe', phonetic: '/bɪˈliːv/', meaning: 'v. 相信；认为', example: 'I believe you are right.', exampleZh: '我相信你是对的。', pos: 'v.', level: 'core' },

  // ==================== Day 4 (121-160) ====================
  { word: 'belong', phonetic: '/bɪˈlɒŋ/', meaning: 'v. 属于', example: 'This book belongs to me.', exampleZh: '这本书是我的。', pos: 'v.', level: 'core' },
  { word: 'below', phonetic: '/bɪˈləʊ/', meaning: 'prep. 在……下面', example: 'The temperature is below zero.', exampleZh: '气温在零度以下。', pos: 'prep.', level: 'core' },
  { word: 'beside', phonetic: '/bɪˈsaɪd/', meaning: 'prep. 在……旁边', example: 'She sat beside me.', exampleZh: '她坐在我旁边。', pos: 'prep.', level: 'core' },
  { word: 'best', phonetic: '/best/', meaning: 'adj. 最好的', example: 'She is my best friend.', exampleZh: '她是我最好的朋友。', pos: 'adj.', level: 'core' },
  { word: 'better', phonetic: '/ˈbetə/', meaning: 'adj. 更好的', example: 'Health is better than wealth.', exampleZh: '健康胜于财富。', pos: 'adj.', level: 'core' },
  { word: 'between', phonetic: '/bɪˈtwiːn/', meaning: 'prep. 在……之间', example: 'Sit between Tom and me.', exampleZh: '坐在汤姆和我之间。', pos: 'prep.', level: 'core' },
  { word: 'beyond', phonetic: '/bɪˈjɒnd/', meaning: 'prep. 超过；在另一边', example: 'The road goes beyond the hill.', exampleZh: '路延伸到山的那边。', pos: 'prep.', level: 'core' },
  { word: 'big', phonetic: '/bɪɡ/', meaning: 'adj. 大的', example: 'They live in a big house.', exampleZh: '他们住在一所大房子里。', pos: 'adj.', level: 'core' },
  { word: 'bike', phonetic: '/baɪk/', meaning: 'n. 自行车', example: 'He rides a bike to school.', exampleZh: '他骑车上学。', pos: 'n.', level: 'core' },
  { word: 'bill', phonetic: '/bɪl/', meaning: 'n. 账单', example: 'Please pay the bill.', exampleZh: '请付账单。', pos: 'n.', level: 'core' },
  { word: 'bird', phonetic: '/bɜːd/', meaning: 'n. 鸟', example: 'Birds can fly.', exampleZh: '鸟会飞。', pos: 'n.', level: 'core' },
  { word: 'birth', phonetic: '/bɜːθ/', meaning: 'n. 出生；诞生', example: 'She gave birth to a boy.', exampleZh: '她生了一个男孩。', pos: 'n.', level: 'core' },
  { word: 'bit', phonetic: '/bɪt/', meaning: 'n. 一点；少量', example: 'Wait a bit, please.', exampleZh: '请稍等一下。', pos: 'n.', level: 'core' },
  { word: 'black', phonetic: '/blæk/', meaning: 'adj. 黑色的', example: 'She has black hair.', exampleZh: '她有黑发。', pos: 'adj.', level: 'core' },
  { word: 'block', phonetic: '/blɒk/', meaning: 'n. 街区 v. 阻塞', example: 'The road is blocked.', exampleZh: '路被堵住了。', pos: 'v.', level: 'core' },
  { word: 'blood', phonetic: '/blʌd/', meaning: 'n. 血液', example: 'He donated blood.', exampleZh: '他献血了。', pos: 'n.', level: 'core' },
  { word: 'blue', phonetic: '/bluː/', meaning: 'adj. 蓝色的', example: 'The sky is blue.', exampleZh: '天空是蓝色的。', pos: 'adj.', level: 'core' },
  { word: 'board', phonetic: '/bɔːd/', meaning: 'n. 板；委员会 v. 登上', example: 'Please board the plane.', exampleZh: '请登机。', pos: 'v.', level: 'core' },
  { word: 'body', phonetic: '/ˈbɒdi/', meaning: 'n. 身体', example: 'Take care of your body.', exampleZh: '照顾好你的身体。', pos: 'n.', level: 'core' },
  { word: 'book', phonetic: '/bʊk/', meaning: 'n. 书 v. 预订', example: 'I booked a room online.', exampleZh: '我在网上订了房间。', pos: 'n.', level: 'core' },
  { word: 'born', phonetic: '/bɔːn/', meaning: 'v. 出生', example: 'He was born in 1990.', exampleZh: '他出生于1990年。', pos: 'v.', level: 'core' },
  { word: 'borrow', phonetic: '/ˈbɒrəʊ/', meaning: 'v. 借；借入', example: 'May I borrow your pen?', exampleZh: '可以借你的笔吗？', pos: 'v.', level: 'core' },
  { word: 'boss', phonetic: '/bɒs/', meaning: 'n. 老板；上司', example: 'My boss is very kind.', exampleZh: '我的老板很好。', pos: 'n.', level: 'core' },
  { word: 'both', phonetic: '/bəʊθ/', meaning: 'adj. 两个的 pron. 两者', example: 'Both of them are smart.', exampleZh: '他们两个都很聪明。', pos: 'adj.', level: 'core' },
  { word: 'bottle', phonetic: '/ˈbɒtl/', meaning: 'n. 瓶子', example: 'He drank a bottle of water.', exampleZh: '他喝了一瓶水。', pos: 'n.', level: 'core' },
  { word: 'bottom', phonetic: '/ˈbɒtəm/', meaning: 'n. 底部', example: 'The answer is at the bottom.', exampleZh: '答案在底部。', pos: 'n.', level: 'core' },
  { word: 'box', phonetic: '/bɒks/', meaning: 'n. 盒子', example: 'Put the toy in the box.', exampleZh: '把玩具放进盒子里。', pos: 'n.', level: 'core' },
  { word: 'boy', phonetic: '/bɔɪ/', meaning: 'n. 男孩', example: 'The boy is playing.', exampleZh: '男孩在玩耍。', pos: 'n.', level: 'core' },
  { word: 'brain', phonetic: '/breɪn/', meaning: 'n. 大脑', example: 'Use your brain.', exampleZh: '动动脑子。', pos: 'n.', level: 'core' },
  { word: 'branch', phonetic: '/brɑːntʃ/', meaning: 'n. 树枝；分支', example: 'The bird sat on a branch.', exampleZh: '鸟停在树枝上。', pos: 'n.', level: 'core' },
  { word: 'brand', phonetic: '/brænd/', meaning: 'n. 品牌', example: 'What is your favorite brand?', exampleZh: '你最喜欢什么品牌？', pos: 'n.', level: 'core' },
  { word: 'brave', phonetic: '/breɪv/', meaning: 'adj. 勇敢的', example: 'He is a brave soldier.', exampleZh: '他是个勇敢的士兵。', pos: 'adj.', level: 'core' },
  { word: 'bread', phonetic: '/bred/', meaning: 'n. 面包', example: 'I eat bread for breakfast.', exampleZh: '我早餐吃面包。', pos: 'n.', level: 'core' },
  { word: 'break', phonetic: '/breɪk/', meaning: 'v. 打破 n. 休息', example: 'He broke the window.', exampleZh: '他打破了窗户。', pos: 'v.', level: 'core' },
  { word: 'breakfast', phonetic: '/ˈbrekfəst/', meaning: 'n. 早餐', example: 'I had breakfast at seven.', exampleZh: '我七点吃了早餐。', pos: 'n.', level: 'core' },
  { word: 'breath', phonetic: '/breθ/', meaning: 'n. 呼吸', example: 'Take a deep breath.', exampleZh: '深呼吸。', pos: 'n.', level: 'core' },
  { word: 'bridge', phonetic: '/brɪdʒ/', meaning: 'n. 桥', example: 'We crossed the bridge.', exampleZh: '我们过了桥。', pos: 'n.', level: 'core' },
  { word: 'brief', phonetic: '/briːf/', meaning: 'adj. 简短的', example: 'Keep your speech brief.', exampleZh: '发言要简短。', pos: 'adj.', level: 'core' },
  { word: 'bright', phonetic: '/braɪt/', meaning: 'adj. 明亮的；聪明的', example: 'The sun is very bright.', exampleZh: '阳光很明亮。', pos: 'adj.', level: 'core' },
  { word: 'bring', phonetic: '/brɪŋ/', meaning: 'v. 带来', example: 'Please bring your book.', exampleZh: '请带上你的书。', pos: 'v.', level: 'core' },
  { word: 'broad', phonetic: '/brɔːd/', meaning: 'adj. 宽的；广泛的', example: 'He has broad shoulders.', exampleZh: '他肩膀很宽。', pos: 'adj.', level: 'core' },

  // ==================== Day 5 (161-200) ====================
  { word: 'brother', phonetic: '/ˈbrʌðə/', meaning: 'n. 兄弟', example: 'My brother is a teacher.', exampleZh: '我哥哥是老师。', pos: 'n.', level: 'core' },
  { word: 'build', phonetic: '/bɪld/', meaning: 'v. 建造', example: 'They built a new school.', exampleZh: '他们建了一所新学校。', pos: 'v.', level: 'core' },
  { word: 'building', phonetic: '/ˈbɪldɪŋ/', meaning: 'n. 建筑物', example: 'That building is very tall.', exampleZh: '那栋楼很高。', pos: 'n.', level: 'core' },
  { word: 'bus', phonetic: '/bʌs/', meaning: 'n. 公共汽车', example: 'I take the bus to work.', exampleZh: '我坐公交车上班。', pos: 'n.', level: 'core' },
  { word: 'business', phonetic: '/ˈbɪznəs/', meaning: 'n. 商业；生意', example: 'Business is good this year.', exampleZh: '今年生意不错。', pos: 'n.', level: 'core' },
  { word: 'busy', phonetic: '/ˈbɪzi/', meaning: 'adj. 忙的', example: 'I am busy with homework.', exampleZh: '我忙着做作业。', pos: 'adj.', level: 'core' },
  { word: 'but', phonetic: '/bʌt/', meaning: 'conj. 但是', example: 'I want to go, but I cannot.', exampleZh: '我想去，但不能。', pos: 'conj.', level: 'core' },
  { word: 'buy', phonetic: '/baɪ/', meaning: 'v. 买', example: 'She bought a new dress.', exampleZh: '她买了一条新裙子。', pos: 'v.', level: 'core' },
  { word: 'cake', phonetic: '/keɪk/', meaning: 'n. 蛋糕', example: 'She made a birthday cake.', exampleZh: '她做了一个生日蛋糕。', pos: 'n.', level: 'core' },
  { word: 'call', phonetic: '/kɔːl/', meaning: 'v. 打电话 n. 电话', example: 'I will call you later.', exampleZh: '我稍后给你打电话。', pos: 'v.', level: 'core' },
  { word: 'calm', phonetic: '/kɑːm/', meaning: 'adj. 平静的 v. 使平静', example: 'Please stay calm.', exampleZh: '请保持冷静。', pos: 'adj.', level: 'core' },
  { word: 'camp', phonetic: '/kæmp/', meaning: 'n. 营地 v. 露营', example: 'We camped by the lake.', exampleZh: '我们在湖边露营。', pos: 'n.', level: 'core' },
  { word: 'cancel', phonetic: '/ˈkænsl/', meaning: 'v. 取消', example: 'The flight was canceled.', exampleZh: '航班被取消了。', pos: 'v.', level: 'core' },
  { word: 'capital', phonetic: '/ˈkæpɪtl/', meaning: 'n. 首都；资本', example: 'Beijing is the capital of China.', exampleZh: '北京是中国的首都。', pos: 'n.', level: 'core' },
  { word: 'captain', phonetic: '/ˈkæptɪn/', meaning: 'n. 队长；船长', example: 'The captain led the team.', exampleZh: '队长带领了团队。', pos: 'n.', level: 'core' },
  { word: 'car', phonetic: '/kɑː/', meaning: 'n. 汽车', example: 'He drives a red car.', exampleZh: '他开一辆红色的车。', pos: 'n.', level: 'core' },
  { word: 'card', phonetic: '/kɑːd/', meaning: 'n. 卡片', example: 'Send me a postcard.', exampleZh: '给我寄张明信片。', pos: 'n.', level: 'core' },
  { word: 'care', phonetic: '/keə/', meaning: 'n. 关心 v. 在乎', example: 'She cares about others.', exampleZh: '她关心别人。', pos: 'v.', level: 'core' },
  { word: 'career', phonetic: '/kəˈrɪə/', meaning: 'n. 职业；生涯', example: 'She has a good career.', exampleZh: '她有一份好职业。', pos: 'n.', level: 'core' },
  { word: 'careful', phonetic: '/ˈkeəfl/', meaning: 'adj. 小心的', example: 'Be careful on the road.', exampleZh: '路上小心。', pos: 'adj.', level: 'core' },
  { word: 'carry', phonetic: '/ˈkæri/', meaning: 'v. 搬运；携带', example: 'He carried the box upstairs.', exampleZh: '他把箱子搬上了楼。', pos: 'v.', level: 'core' },
  { word: 'case', phonetic: '/keɪs/', meaning: 'n. 情况；案例', example: 'In that case, I will go.', exampleZh: '那样的话，我就去。', pos: 'n.', level: 'core' },
  { word: 'cash', phonetic: '/kæʃ/', meaning: 'n. 现金', example: 'Pay in cash, please.', exampleZh: '请用现金支付。', pos: 'n.', level: 'core' },
  { word: 'cat', phonetic: '/kæt/', meaning: 'n. 猫', example: 'The cat is on the sofa.', exampleZh: '猫在沙发上。', pos: 'n.', level: 'core' },
  { word: 'catch', phonetic: '/kætʃ/', meaning: 'v. 抓住；赶上', example: 'Catch the ball!', exampleZh: '接住球！', pos: 'v.', level: 'core' },
  { word: 'cause', phonetic: '/kɔːz/', meaning: 'n. 原因 v. 导致', example: 'What caused the fire?', exampleZh: '什么引起了火灾？', pos: 'v.', level: 'core' },
  { word: 'celebrate', phonetic: '/ˈselɪbreɪt/', meaning: 'v. 庆祝', example: 'We celebrate the New Year.', exampleZh: '我们庆祝新年。', pos: 'v.', level: 'core' },
  { word: 'center', phonetic: '/ˈsentə/', meaning: 'n. 中心', example: 'The shop is in the city center.', exampleZh: '商店在市中心。', pos: 'n.', level: 'core' },
  { word: 'central', phonetic: '/ˈsentrəl/', meaning: 'adj. 中心的；中央的', example: 'The central idea is clear.', exampleZh: '中心思想很清楚。', pos: 'adj.', level: 'core' },
  { word: 'century', phonetic: '/ˈsentʃəri/', meaning: 'n. 世纪', example: 'This is the 21st century.', exampleZh: '这是21世纪。', pos: 'n.', level: 'core' },
  { word: 'certain', phonetic: '/ˈsɜːtn/', meaning: 'adj. 确定的；某个', example: 'I am certain he will come.', exampleZh: '我确定他会来。', pos: 'adj.', level: 'core' },
  { word: 'chain', phonetic: '/tʃeɪn/', meaning: 'n. 链条', example: 'The dog is on a chain.', exampleZh: '狗被链子拴着。', pos: 'n.', level: 'core' },
  { word: 'chair', phonetic: '/tʃeə/', meaning: 'n. 椅子', example: 'Sit on the chair.', exampleZh: '坐在椅子上。', pos: 'n.', level: 'core' },
  { word: 'chance', phonetic: '/tʃɑːns/', meaning: 'n. 机会', example: 'Give me a chance.', exampleZh: '给我一个机会。', pos: 'n.', level: 'core' },
  { word: 'change', phonetic: '/tʃeɪndʒ/', meaning: 'v. 改变 n. 零钱', example: 'He changed his mind.', exampleZh: '他改变了主意。', pos: 'v.', level: 'core' },
  { word: 'channel', phonetic: '/ˈtʃænl/', meaning: 'n. 频道；渠道', example: 'Change the TV channel.', exampleZh: '换电视频道。', pos: 'n.', level: 'core' },
  { word: 'character', phonetic: '/ˈkærəktə/', meaning: 'n. 性格；角色', example: 'He has a strong character.', exampleZh: '他性格坚强。', pos: 'n.', level: 'core' },
  { word: 'charge', phonetic: '/tʃɑːdʒ/', meaning: 'v. 收费 n. 费用', example: 'How much do you charge?', exampleZh: '你收多少钱？', pos: 'v.', level: 'core' },
  { word: 'cheap', phonetic: '/tʃiːp/', meaning: 'adj. 便宜的', example: 'This shirt is very cheap.', exampleZh: '这件衬衫很便宜。', pos: 'adj.', level: 'core' },
  { word: 'check', phonetic: '/tʃek/', meaning: 'v. 检查 n. 支票', example: 'Please check your answer.', exampleZh: '请检查你的答案。', pos: 'v.', level: 'core' },
  { word: 'child', phonetic: '/tʃaɪld/', meaning: 'n. 孩子', example: 'The child is happy.', exampleZh: '孩子很开心。', pos: 'n.', level: 'core' },

  // ==================== Day 6 (201-240) ====================
  { word: 'choice', phonetic: '/tʃɔɪs/', meaning: 'n. 选择', example: 'You made a good choice.', exampleZh: '你做了一个好选择。', pos: 'n.', level: 'core' },
  { word: 'choose', phonetic: '/tʃuːz/', meaning: 'v. 选择', example: 'Choose what you like.', exampleZh: '选你喜欢的。', pos: 'v.', level: 'core' },
  { word: 'church', phonetic: '/tʃɜːtʃ/', meaning: 'n. 教堂', example: 'They go to church on Sunday.', exampleZh: '他们周日去教堂。', pos: 'n.', level: 'core' },
  { word: 'circle', phonetic: '/ˈsɜːkl/', meaning: 'n. 圆圈 v. 圈出', example: 'Draw a circle on the paper.', exampleZh: '在纸上画一个圆。', pos: 'n.', level: 'core' },
  { word: 'city', phonetic: '/ˈsɪti/', meaning: 'n. 城市', example: 'Shanghai is a big city.', exampleZh: '上海是个大城市。', pos: 'n.', level: 'core' },
  { word: 'claim', phonetic: '/kleɪm/', meaning: 'v. 声称 n. 要求', example: 'He claimed he was innocent.', exampleZh: '他声称自己是无辜的。', pos: 'v.', level: 'core' },
  { word: 'class', phonetic: '/klɑːs/', meaning: 'n. 班级；课', example: 'Our class has 30 students.', exampleZh: '我们班有30个学生。', pos: 'n.', level: 'core' },
  { word: 'clean', phonetic: '/kliːn/', meaning: 'adj. 干净的 v. 打扫', example: 'Please clean the room.', exampleZh: '请打扫房间。', pos: 'adj.', level: 'core' },
  { word: 'clear', phonetic: '/klɪə/', meaning: 'adj. 清楚的', example: 'The water is clear.', exampleZh: '水很清澈。', pos: 'adj.', level: 'core' },
  { word: 'climate', phonetic: '/ˈklaɪmət/', meaning: 'n. 气候', example: 'The climate is changing.', exampleZh: '气候在变化。', pos: 'n.', level: 'core' },
  { word: 'climb', phonetic: '/klaɪm/', meaning: 'v. 攀登', example: 'They climbed the mountain.', exampleZh: '他们爬了山。', pos: 'v.', level: 'core' },
  { word: 'clock', phonetic: '/klɒk/', meaning: 'n. 时钟', example: 'The clock is on the wall.', exampleZh: '钟在墙上。', pos: 'n.', level: 'core' },
  { word: 'close', phonetic: '/kləʊz/', meaning: 'v. 关闭 adj. 近的', example: 'Close the door, please.', exampleZh: '请关上门。', pos: 'v.', level: 'core' },
  { word: 'clothes', phonetic: '/kləʊðz/', meaning: 'n. 衣服', example: 'She washed the clothes.', exampleZh: '她洗了衣服。', pos: 'n.', level: 'core' },
  { word: 'cloud', phonetic: '/klaʊd/', meaning: 'n. 云', example: 'The clouds are white.', exampleZh: '云是白色的。', pos: 'n.', level: 'core' },
  { word: 'club', phonetic: '/klʌb/', meaning: 'n. 俱乐部', example: 'He joined the chess club.', exampleZh: '他加入了象棋俱乐部。', pos: 'n.', level: 'core' },
  { word: 'coach', phonetic: '/kəʊtʃ/', meaning: 'n. 教练', example: 'The coach trained the team.', exampleZh: '教练训练了队伍。', pos: 'n.', level: 'core' },
  { word: 'coast', phonetic: '/kəʊst/', meaning: 'n. 海岸', example: 'We drove along the coast.', exampleZh: '我们沿着海岸开车。', pos: 'n.', level: 'core' },
  { word: 'coat', phonetic: '/kəʊt/', meaning: 'n. 外套', example: 'Put on your coat.', exampleZh: '穿上你的外套。', pos: 'n.', level: 'core' },
  { word: 'code', phonetic: '/kəʊd/', meaning: 'n. 密码；代码', example: 'Enter the code here.', exampleZh: '在这里输入密码。', pos: 'n.', level: 'core' },
  { word: 'coffee', phonetic: '/ˈkɒfi/', meaning: 'n. 咖啡', example: 'I drink coffee every morning.', exampleZh: '我每天早上喝咖啡。', pos: 'n.', level: 'core' },
  { word: 'cold', phonetic: '/kəʊld/', meaning: 'adj. 冷的 n. 感冒', example: 'It is cold outside.', exampleZh: '外面很冷。', pos: 'adj.', level: 'core' },
  { word: 'collect', phonetic: '/kəˈlekt/', meaning: 'v. 收集', example: 'She collects stamps.', exampleZh: '她收集邮票。', pos: 'v.', level: 'core' },
  { word: 'college', phonetic: '/ˈkɒlɪdʒ/', meaning: 'n. 学院；大学', example: 'He goes to college.', exampleZh: '他上大学。', pos: 'n.', level: 'core' },
  { word: 'color', phonetic: '/ˈkʌlə/', meaning: 'n. 颜色', example: 'What color do you like?', exampleZh: '你喜欢什么颜色？', pos: 'n.', level: 'core' },
  { word: 'come', phonetic: '/kʌm/', meaning: 'v. 来', example: 'Come here, please.', exampleZh: '请过来。', pos: 'v.', level: 'core' },
  { word: 'comfort', phonetic: '/ˈkʌmfət/', meaning: 'n. 舒适 v. 安慰', example: 'The chair gives comfort.', exampleZh: '这把椅子很舒适。', pos: 'n.', level: 'core' },
  { word: 'command', phonetic: '/kəˈmɑːnd/', meaning: 'v. 命令 n. 命令', example: 'He commanded the army.', exampleZh: '他指挥了军队。', pos: 'v.', level: 'core' },
  { word: 'comment', phonetic: '/ˈkɒment/', meaning: 'n. 评论 v. 评论', example: 'Leave a comment below.', exampleZh: '在下方留言。', pos: 'n.', level: 'core' },
  { word: 'common', phonetic: '/ˈkɒmən/', meaning: 'adj. 常见的；共同的', example: 'Smith is a common name.', exampleZh: '史密斯是个常见的名字。', pos: 'adj.', level: 'core' },
  { word: 'community', phonetic: '/kəˈmjuːnəti/', meaning: 'n. 社区', example: 'Our community is very friendly.', exampleZh: '我们的社区很友好。', pos: 'n.', level: 'core' },
  { word: 'company', phonetic: '/ˈkʌmpəni/', meaning: 'n. 公司', example: 'He works in a big company.', exampleZh: '他在一家大公司工作。', pos: 'n.', level: 'core' },
  { word: 'compare', phonetic: '/kəmˈpeə/', meaning: 'v. 比较', example: 'Compare the two pictures.', exampleZh: '比较这两幅画。', pos: 'v.', level: 'core' },
  { word: 'compete', phonetic: '/kəmˈpiːt/', meaning: 'v. 竞争', example: 'They compete for the prize.', exampleZh: '他们为奖品竞争。', pos: 'v.', level: 'core' },
  { word: 'complete', phonetic: '/kəmˈpliːt/', meaning: 'v. 完成 adj. 完整的', example: 'Complete the form.', exampleZh: '填写表格。', pos: 'v.', level: 'core' },
  { word: 'computer', phonetic: '/kəmˈpjuːtə/', meaning: 'n. 计算机', example: 'I use a computer at work.', exampleZh: '我上班用电脑。', pos: 'n.', level: 'core' },
  { word: 'concern', phonetic: '/kənˈsɜːn/', meaning: 'v. 关心 n. 关心', example: 'This concerns everyone.', exampleZh: '这关系到每个人。', pos: 'v.', level: 'core' },
  { word: 'condition', phonetic: '/kənˈdɪʃn/', meaning: 'n. 条件；状况', example: 'The car is in good condition.', exampleZh: '车况良好。', pos: 'n.', level: 'core' },
  { word: 'conference', phonetic: '/ˈkɒnfərəns/', meaning: 'n. 会议', example: 'She attended a conference.', exampleZh: '她参加了一个会议。', pos: 'n.', level: 'core' },
  { word: 'confirm', phonetic: '/kənˈfɜːm/', meaning: 'v. 确认', example: 'Please confirm your booking.', exampleZh: '请确认你的预订。', pos: 'v.', level: 'core' },
  { word: 'connect', phonetic: '/kəˈnekt/', meaning: 'v. 连接', example: 'Connect the two wires.', exampleZh: '把两根线连起来。', pos: 'v.', level: 'core' },

  // ==================== Day 7 (241-280) ====================
  { word: 'consider', phonetic: '/kənˈsɪdə/', meaning: 'v. 考虑', example: 'Please consider my offer.', exampleZh: '请考虑我的提议。', pos: 'v.', level: 'core' },
  { word: 'consist', phonetic: '/kənˈsɪst/', meaning: 'v. 组成；构成', example: 'Water consists of hydrogen and oxygen.', exampleZh: '水由氢和氧组成。', pos: 'v.', level: 'core' },
  { word: 'constantly', phonetic: '/ˈkɒnstəntli/', meaning: 'adv. 不断地', example: 'He is constantly busy.', exampleZh: '他总是很忙。', pos: 'adv.', level: 'core' },
  { word: 'contain', phonetic: '/kənˈteɪn/', meaning: 'v. 包含', example: 'The box contains books.', exampleZh: '箱子里有书。', pos: 'v.', level: 'core' },
  { word: 'content', phonetic: '/ˈkɒntent/', meaning: 'n. 内容 adj. 满足的', example: 'I am content with my life.', exampleZh: '我对生活很满意。', pos: 'adj.', level: 'core' },
  { word: 'context', phonetic: '/ˈkɒntekst/', meaning: 'n. 上下文；背景', example: 'Guess the meaning from context.', exampleZh: '根据上下文猜意思。', pos: 'n.', level: 'core' },
  { word: 'continue', phonetic: '/kənˈtɪnjuː/', meaning: 'v. 继续', example: 'Please continue your work.', exampleZh: '请继续你的工作。', pos: 'v.', level: 'core' },
  { word: 'control', phonetic: '/kənˈtrəʊl/', meaning: 'v. 控制 n. 控制', example: 'He cannot control his anger.', exampleZh: '他控制不住自己的愤怒。', pos: 'v.', level: 'core' },
  { word: 'convenient', phonetic: '/kənˈviːniənt/', meaning: 'adj. 方便的', example: 'It is convenient to live here.', exampleZh: '住在这里很方便。', pos: 'adj.', level: 'core' },
  { word: 'conversation', phonetic: '/ˌkɒnvəˈseɪʃn/', meaning: 'n. 对话；交谈', example: 'We had a long conversation.', exampleZh: '我们进行了长谈。', pos: 'n.', level: 'core' },
  { word: 'convince', phonetic: '/kənˈvɪns/', meaning: 'v. 说服', example: 'I convinced him to try.', exampleZh: '我说服他去尝试。', pos: 'v.', level: 'core' },
  { word: 'cook', phonetic: '/kʊk/', meaning: 'v. 做饭 n. 厨师', example: 'She cooks dinner every day.', exampleZh: '她每天做晚饭。', pos: 'v.', level: 'core' },
  { word: 'cool', phonetic: '/kuːl/', meaning: 'adj. 凉的；酷的', example: 'It is cool today.', exampleZh: '今天很凉爽。', pos: 'adj.', level: 'core' },
  { word: 'copy', phonetic: '/ˈkɒpi/', meaning: 'v. 复制 n. 副本', example: 'Copy this document.', exampleZh: '复制这份文件。', pos: 'v.', level: 'core' },
  { word: 'corner', phonetic: '/ˈkɔːnə/', meaning: 'n. 角落', example: 'The shop is on the corner.', exampleZh: '商店在拐角处。', pos: 'n.', level: 'core' },
  { word: 'correct', phonetic: '/kəˈrekt/', meaning: 'adj. 正确的 v. 纠正', example: 'Your answer is correct.', exampleZh: '你的答案是对的。', pos: 'adj.', level: 'core' },
  { word: 'cost', phonetic: '/kɒst/', meaning: 'v. 花费 n. 成本', example: 'The book costs 20 yuan.', exampleZh: '这本书20元。', pos: 'v.', level: 'core' },
  { word: 'could', phonetic: '/kʊd/', meaning: 'v. 能（can的过去式）', example: 'Could you help me?', exampleZh: '你能帮我吗？', pos: 'v.', level: 'core' },
  { word: 'count', phonetic: '/kaʊnt/', meaning: 'v. 数数；重要', example: 'Count the apples.', exampleZh: '数一数苹果。', pos: 'v.', level: 'core' },
  { word: 'country', phonetic: '/ˈkʌntri/', meaning: 'n. 国家', example: 'China is a great country.', exampleZh: '中国是个伟大的国家。', pos: 'n.', level: 'core' },
  { word: 'couple', phonetic: '/ˈkʌpl/', meaning: 'n. 一对；夫妻', example: 'They are a nice couple.', exampleZh: '他们是很好的一对。', pos: 'n.', level: 'core' },
  { word: 'course', phonetic: '/kɔːs/', meaning: 'n. 课程；过程', example: 'I took a English course.', exampleZh: '我选了英语课。', pos: 'n.', level: 'core' },
  { word: 'court', phonetic: '/kɔːt/', meaning: 'n. 法庭；球场', example: 'The court will decide.', exampleZh: '法庭将做出裁决。', pos: 'n.', level: 'core' },
  { word: 'cover', phonetic: '/ˈkʌvə/', meaning: 'v. 覆盖 n. 封面', example: 'Cover the food.', exampleZh: '把食物盖上。', pos: 'v.', level: 'core' },
  { word: 'create', phonetic: '/kriˈeɪt/', meaning: 'v. 创造', example: 'She created a new design.', exampleZh: '她创造了一个新设计。', pos: 'v.', level: 'core' },
  { word: 'credit', phonetic: '/ˈkredɪt/', meaning: 'n. 信用；学分', example: 'He has good credit.', exampleZh: '他信用很好。', pos: 'n.', level: 'core' },
  { word: 'crew', phonetic: '/kruː/', meaning: 'n. 全体船员；团队', example: 'The crew worked hard.', exampleZh: '全体船员很努力。', pos: 'n.', level: 'core' },
  { word: 'crime', phonetic: '/kraɪm/', meaning: 'n. 犯罪', example: 'Crime is a serious problem.', exampleZh: '犯罪是个严重问题。', pos: 'n.', level: 'core' },
  { word: 'crisis', phonetic: '/ˈkraɪsɪs/', meaning: 'n. 危机', example: 'The country faces a crisis.', exampleZh: '国家面临危机。', pos: 'n.', level: 'core' },
  { word: 'criticize', phonetic: '/ˈkrɪtɪsaɪz/', meaning: 'v. 批评', example: 'Do not criticize others.', exampleZh: '不要批评别人。', pos: 'v.', level: 'core' },
  { word: 'cross', phonetic: '/krɒs/', meaning: 'v. 穿过 n. 十字', example: 'Do not cross the road.', exampleZh: '不要穿马路。', pos: 'v.', level: 'core' },
  { word: 'crowd', phonetic: '/kraʊd/', meaning: 'n. 人群 v. 拥挤', example: 'A crowd gathered outside.', exampleZh: '一群人聚在外面。', pos: 'n.', level: 'core' },
  { word: 'cry', phonetic: '/kraɪ/', meaning: 'v. 哭', example: 'The baby is crying.', exampleZh: '婴儿在哭。', pos: 'v.', level: 'core' },
  { word: 'culture', phonetic: '/ˈkʌltʃə/', meaning: 'n. 文化', example: 'I love Chinese culture.', exampleZh: '我喜欢中国文化。', pos: 'n.', level: 'core' },
  { word: 'cup', phonetic: '/kʌp/', meaning: 'n. 杯子', example: 'A cup of tea, please.', exampleZh: '请来一杯茶。', pos: 'n.', level: 'core' },
  { word: 'current', phonetic: '/ˈkʌrənt/', meaning: 'adj. 当前的 n. 电流', example: 'What is the current time?', exampleZh: '现在几点了？', pos: 'adj.', level: 'core' },
  { word: 'custom', phonetic: '/ˈkʌstəm/', meaning: 'n. 习俗', example: 'It is a local custom.', exampleZh: '这是当地习俗。', pos: 'n.', level: 'core' },
  { word: 'customer', phonetic: '/ˈkʌstəmə/', meaning: 'n. 顾客', example: 'The customer is happy.', exampleZh: '顾客很满意。', pos: 'n.', level: 'core' },
  { word: 'cut', phonetic: '/kʌt/', meaning: 'v. 切；割', example: 'Cut the apple in half.', exampleZh: '把苹果切成两半。', pos: 'v.', level: 'core' },
  { word: 'damage', phonetic: '/ˈdæmɪdʒ/', meaning: 'n. 损害 v. 损害', example: 'The storm caused damage.', exampleZh: '暴风雨造成了损害。', pos: 'n.', level: 'core' },

  // ==================== Day 8 (281-320) ====================
  { word: 'dance', phonetic: '/dɑːns/', meaning: 'v. 跳舞 n. 舞蹈', example: 'They dance happily.', exampleZh: '他们快乐地跳舞。', pos: 'v.', level: 'core' },
  { word: 'danger', phonetic: '/ˈdeɪndʒə/', meaning: 'n. 危险', example: 'His life is in danger.', exampleZh: '他有生命危险。', pos: 'n.', level: 'core' },
  { word: 'dark', phonetic: '/dɑːk/', meaning: 'adj. 黑暗的', example: 'It is dark outside.', exampleZh: '外面很黑。', pos: 'adj.', level: 'core' },
  { word: 'data', phonetic: '/ˈdeɪtə/', meaning: 'n. 数据', example: 'We need more data.', exampleZh: '我们需要更多数据。', pos: 'n.', level: 'core' },
  { word: 'date', phonetic: '/deɪt/', meaning: 'n. 日期', example: 'What is the date today?', exampleZh: '今天几号？', pos: 'n.', level: 'core' },
  { word: 'daughter', phonetic: '/ˈdɔːtə/', meaning: 'n. 女儿', example: 'She has a daughter.', exampleZh: '她有一个女儿。', pos: 'n.', level: 'core' },
  { word: 'day', phonetic: '/deɪ/', meaning: 'n. 天；日子', example: 'Have a nice day!', exampleZh: '祝你有美好的一天！', pos: 'n.', level: 'core' },
  { word: 'dead', phonetic: '/ded/', meaning: 'adj. 死的', example: 'The flower is dead.', exampleZh: '花枯死了。', pos: 'adj.', level: 'core' },
  { word: 'deal', phonetic: '/diːl/', meaning: 'v. 处理 n. 交易', example: 'I will deal with it.', exampleZh: '我会处理这件事。', pos: 'v.', level: 'core' },
  { word: 'dear', phonetic: '/dɪə/', meaning: 'adj. 亲爱的', example: 'Dear friend, how are you?', exampleZh: '亲爱的朋友，你好吗？', pos: 'adj.', level: 'core' },
  { word: 'death', phonetic: '/deθ/', meaning: 'n. 死亡', example: 'His death was sudden.', exampleZh: '他的死很突然。', pos: 'n.', level: 'core' },
  { word: 'debate', phonetic: '/dɪˈbeɪt/', meaning: 'n. 辩论 v. 辩论', example: 'They had a heated debate.', exampleZh: '他们进行了激烈的辩论。', pos: 'n.', level: 'core' },
  { word: 'decade', phonetic: '/ˈdekeɪd/', meaning: 'n. 十年', example: 'Things changed in a decade.', exampleZh: '十年间事情变了。', pos: 'n.', level: 'core' },
  { word: 'decide', phonetic: '/dɪˈsaɪd/', meaning: 'v. 决定', example: 'I decided to go.', exampleZh: '我决定去。', pos: 'v.', level: 'core' },
  { word: 'decision', phonetic: '/dɪˈsɪʒn/', meaning: 'n. 决定', example: 'It was a hard decision.', exampleZh: '这是个艰难的决定。', pos: 'n.', level: 'core' },
  { word: 'declare', phonetic: '/dɪˈkleə/', meaning: 'v. 宣布', example: 'He declared the result.', exampleZh: '他宣布了结果。', pos: 'v.', level: 'core' },
  { word: 'deep', phonetic: '/diːp/', meaning: 'adj. 深的', example: 'The river is very deep.', exampleZh: '河水很深。', pos: 'adj.', level: 'core' },
  { word: 'defeat', phonetic: '/dɪˈfiːt/', meaning: 'v. 击败 n. 失败', example: 'We defeated the enemy.', exampleZh: '我们击败了敌人。', pos: 'v.', level: 'core' },
  { word: 'defend', phonetic: '/dɪˈfend/', meaning: 'v. 防御；辩护', example: 'He defended his country.', exampleZh: '他保卫了他的国家。', pos: 'v.', level: 'core' },
  { word: 'define', phonetic: '/dɪˈfaɪn/', meaning: 'v. 定义', example: 'Define this word.', exampleZh: '给这个词下定义。', pos: 'v.', level: 'core' },
  { word: 'degree', phonetic: '/dɪˈɡriː/', meaning: 'n. 程度；学位', example: 'He has a degree in math.', exampleZh: '他有数学学位。', pos: 'n.', level: 'core' },
  { word: 'delay', phonetic: '/dɪˈleɪ/', meaning: 'v. 延迟 n. 延误', example: 'The flight was delayed.', exampleZh: '航班延误了。', pos: 'v.', level: 'core' },
  { word: 'deliver', phonetic: '/dɪˈlɪvə/', meaning: 'v. 递送', example: 'They deliver food.', exampleZh: '他们送餐。', pos: 'v.', level: 'core' },
  { word: 'demand', phonetic: '/dɪˈmɑːnd/', meaning: 'v. 要求 n. 需求', example: 'I demand an answer.', exampleZh: '我要求一个答复。', pos: 'v.', level: 'core' },
  { word: 'depend', phonetic: '/dɪˈpend/', meaning: 'v. 依赖；取决于', example: 'It depends on you.', exampleZh: '这取决于你。', pos: 'v.', level: 'core' },
  { word: 'describe', phonetic: '/dɪˈskraɪb/', meaning: 'v. 描述', example: 'Describe what you saw.', exampleZh: '描述你看到的。', pos: 'v.', level: 'core' },
  { word: 'design', phonetic: '/dɪˈzaɪn/', meaning: 'v. 设计 n. 设计', example: 'She designed the logo.', exampleZh: '她设计了这个标志。', pos: 'v.', level: 'core' },
  { word: 'desire', phonetic: '/dɪˈzaɪə/', meaning: 'n. 欲望 v. 渴望', example: 'He has a desire to learn.', exampleZh: '他有学习的渴望。', pos: 'n.', level: 'core' },
  { word: 'desk', phonetic: '/desk/', meaning: 'n. 书桌', example: 'The book is on the desk.', exampleZh: '书在书桌上。', pos: 'n.', level: 'core' },
  { word: 'destroy', phonetic: '/dɪˈstrɔɪ/', meaning: 'v. 破坏', example: 'The fire destroyed the house.', exampleZh: '火烧毁了房子。', pos: 'v.', level: 'core' },
  { word: 'detail', phonetic: '/ˈdiːteɪl/', meaning: 'n. 细节', example: 'Tell me the details.', exampleZh: '告诉我细节。', pos: 'n.', level: 'core' },
  { word: 'determine', phonetic: '/dɪˈtɜːmɪn/', meaning: 'v. 决定；确定', example: 'We determined the cause.', exampleZh: '我们确定了原因。', pos: 'v.', level: 'core' },
  { word: 'develop', phonetic: '/dɪˈveləp/', meaning: 'v. 发展', example: 'The city develops fast.', exampleZh: '城市发展很快。', pos: 'v.', level: 'core' },
  { word: 'device', phonetic: '/dɪˈvaɪs/', meaning: 'n. 设备', example: 'This is a useful device.', exampleZh: '这是一个有用的设备。', pos: 'n.', level: 'core' },
  { word: 'dictionary', phonetic: '/ˈdɪkʃənri/', meaning: 'n. 词典', example: 'Look it up in the dictionary.', exampleZh: '查词典。', pos: 'n.', level: 'core' },
  { word: 'die', phonetic: '/daɪ/', meaning: 'v. 死', example: 'Plants die without water.', exampleZh: '植物没水会死。', pos: 'v.', level: 'core' },
  { word: 'difference', phonetic: '/ˈdɪfrəns/', meaning: 'n. 不同；差异', example: 'What is the difference?', exampleZh: '有什么区别？', pos: 'n.', level: 'core' },
  { word: 'different', phonetic: '/ˈdɪfrənt/', meaning: 'adj. 不同的', example: 'We are very different.', exampleZh: '我们很不一样。', pos: 'adj.', level: 'core' },
  { word: 'difficult', phonetic: '/ˈdɪfɪkəlt/', meaning: 'adj. 困难的', example: 'The test was difficult.', exampleZh: '考试很难。', pos: 'adj.', level: 'core' },
  { word: 'dinner', phonetic: '/ˈdɪnə/', meaning: 'n. 晚餐', example: 'We had dinner together.', exampleZh: '我们一起吃了晚饭。', pos: 'n.', level: 'core' },

  // ==================== Day 9 (321-360) ====================
  { word: 'direct', phonetic: '/dəˈrekt/', meaning: 'adj. 直接的 v. 指引', example: 'Give a direct answer.', exampleZh: '直接回答。', pos: 'adj.', level: 'core' },
  { word: 'direction', phonetic: '/dəˈrekʃn/', meaning: 'n. 方向', example: 'Which direction is north?', exampleZh: '哪边是北？', pos: 'n.', level: 'core' },
  { word: 'director', phonetic: '/dəˈrektə/', meaning: 'n. 主任；导演', example: 'She is the director.', exampleZh: '她是主任。', pos: 'n.', level: 'core' },
  { word: 'dirty', phonetic: '/ˈdɜːti/', meaning: 'adj. 脏的', example: 'Your hands are dirty.', exampleZh: '你的手很脏。', pos: 'adj.', level: 'core' },
  { word: 'disappear', phonetic: '/ˌdɪsəˈpɪə/', meaning: 'v. 消失', example: 'The sun disappeared.', exampleZh: '太阳消失了。', pos: 'v.', level: 'core' },
  { word: 'discover', phonetic: '/dɪˈskʌvə/', meaning: 'v. 发现', example: 'They discovered a new island.', exampleZh: '他们发现了一个新岛。', pos: 'v.', level: 'core' },
  { word: 'discuss', phonetic: '/dɪˈskʌs/', meaning: 'v. 讨论', example: 'Let us discuss the plan.', exampleZh: '我们讨论一下计划。', pos: 'v.', level: 'core' },
  { word: 'disease', phonetic: '/dɪˈziːz/', meaning: 'n. 疾病', example: 'Heart disease is common.', exampleZh: '心脏病很常见。', pos: 'n.', level: 'core' },
  { word: 'distance', phonetic: '/ˈdɪstəns/', meaning: 'n. 距离', example: 'The distance is short.', exampleZh: '距离很短。', pos: 'n.', level: 'core' },
  { word: 'divide', phonetic: '/dɪˈvaɪd/', meaning: 'v. 分；划分', example: 'Divide it into two parts.', exampleZh: '把它分成两部分。', pos: 'v.', level: 'core' },
  { word: 'doctor', phonetic: '/ˈdɒktə/', meaning: 'n. 医生', example: 'See a doctor if you feel sick.', exampleZh: '不舒服就去看医生。', pos: 'n.', level: 'core' },
  { word: 'document', phonetic: '/ˈdɒkjumənt/', meaning: 'n. 文件', example: 'Sign this document.', exampleZh: '签这份文件。', pos: 'n.', level: 'core' },
  { word: 'dog', phonetic: '/dɒɡ/', meaning: 'n. 狗', example: 'The dog is barking.', exampleZh: '狗在叫。', pos: 'n.', level: 'core' },
  { word: 'door', phonetic: '/dɔː/', meaning: 'n. 门', example: 'Open the door.', exampleZh: '打开门。', pos: 'n.', level: 'core' },
  { word: 'double', phonetic: '/ˈdʌbl/', meaning: 'adj. 双倍的 v. 翻倍', example: 'I want a double room.', exampleZh: '我要一间双人间。', pos: 'adj.', level: 'core' },
  { word: 'doubt', phonetic: '/daʊt/', meaning: 'n. 怀疑 v. 怀疑', example: 'I doubt his story.', exampleZh: '我怀疑他的说法。', pos: 'v.', level: 'core' },
  { word: 'down', phonetic: '/daʊn/', meaning: 'adv. 向下', example: 'Sit down, please.', exampleZh: '请坐下。', pos: 'adv.', level: 'core' },
  { word: 'draw', phonetic: '/drɔː/', meaning: 'v. 画', example: 'She drew a picture.', exampleZh: '她画了一幅画。', pos: 'v.', level: 'core' },
  { word: 'dream', phonetic: '/driːm/', meaning: 'n. 梦想 v. 做梦', example: 'I had a strange dream.', exampleZh: '我做了一个奇怪的梦。', pos: 'n.', level: 'core' },
  { word: 'dress', phonetic: '/dres/', meaning: 'n. 裙子 v. 穿衣', example: 'She wore a red dress.', exampleZh: '她穿了红裙子。', pos: 'n.', level: 'core' },
  { word: 'drink', phonetic: '/drɪŋk/', meaning: 'v. 喝 n. 饮料', example: 'Drink more water.', exampleZh: '多喝水。', pos: 'v.', level: 'core' },
  { word: 'drive', phonetic: '/draɪv/', meaning: 'v. 开车', example: 'He drives to work.', exampleZh: '他开车上班。', pos: 'v.', level: 'core' },
  { word: 'drop', phonetic: '/drɒp/', meaning: 'v. 掉下 n. 滴', example: 'Be careful, do not drop it.', exampleZh: '小心，别掉了。', pos: 'v.', level: 'core' },
  { word: 'drug', phonetic: '/drʌɡ/', meaning: 'n. 药物', example: 'This drug is effective.', exampleZh: '这种药有效。', pos: 'n.', level: 'core' },
  { word: 'during', phonetic: '/ˈdjʊərɪŋ/', meaning: 'prep. 在……期间', example: 'During the meeting, he spoke.', exampleZh: '会议期间他发了言。', pos: 'prep.', level: 'core' },
  { word: 'duty', phonetic: '/ˈdjuːti/', meaning: 'n. 责任；义务', example: 'It is my duty to help.', exampleZh: '帮助是我的责任。', pos: 'n.', level: 'core' },
  { word: 'each', phonetic: '/iːtʃ/', meaning: 'adj. 每个', example: 'Each student got a book.', exampleZh: '每个学生都拿到了书。', pos: 'adj.', level: 'core' },
  { word: 'early', phonetic: '/ˈɜːli/', meaning: 'adv. 早', example: 'I get up early.', exampleZh: '我起得早。', pos: 'adv.', level: 'core' },
  { word: 'earn', phonetic: '/ɜːn/', meaning: 'v. 赚得', example: 'She earns a lot of money.', exampleZh: '她赚很多钱。', pos: 'v.', level: 'core' },
  { word: 'earth', phonetic: '/ɜːθ/', meaning: 'n. 地球', example: 'The earth goes around the sun.', exampleZh: '地球绕着太阳转。', pos: 'n.', level: 'core' },
  { word: 'easy', phonetic: '/ˈiːzi/', meaning: 'adj. 容易的', example: 'This question is easy.', exampleZh: '这个问题很简单。', pos: 'adj.', level: 'core' },
  { word: 'eat', phonetic: '/iːt/', meaning: 'v. 吃', example: 'I eat breakfast at seven.', exampleZh: '我七点吃早餐。', pos: 'v.', level: 'core' },
  { word: 'economy', phonetic: '/ɪˈkɒnəmi/', meaning: 'n. 经济', example: 'The economy is growing.', exampleZh: '经济在增长。', pos: 'n.', level: 'core' },
  { word: 'edge', phonetic: '/edʒ/', meaning: 'n. 边缘', example: 'Do not stand at the edge.', exampleZh: '不要站在边缘。', pos: 'n.', level: 'core' },
  { word: 'education', phonetic: '/ˌedʒuˈkeɪʃn/', meaning: 'n. 教育', example: 'Education is important.', exampleZh: '教育很重要。', pos: 'n.', level: 'core' },
  { word: 'effect', phonetic: '/ɪˈfekt/', meaning: 'n. 影响；效果', example: 'What is the effect?', exampleZh: '有什么效果？', pos: 'n.', level: 'core' },
  { word: 'effort', phonetic: '/ˈefət/', meaning: 'n. 努力', example: 'Make an effort to study.', exampleZh: '努力学习。', pos: 'n.', level: 'core' },
  { word: 'either', phonetic: '/ˈaɪðə/', meaning: 'adj. 任何一个', example: 'Either way is fine.', exampleZh: '哪种方式都行。', pos: 'adj.', level: 'core' },
  { word: 'elect', phonetic: '/ɪˈlekt/', meaning: 'v. 选举', example: 'They elected a new leader.', exampleZh: '他们选了新领导。', pos: 'v.', level: 'core' },
  { word: 'electric', phonetic: '/ɪˈlektrɪk/', meaning: 'adj. 电的', example: 'It is an electric car.', exampleZh: '这是一辆电动车。', pos: 'adj.', level: 'core' },
  { word: 'element', phonetic: '/ˈelɪmənt/', meaning: 'n. 元素；要素', example: 'Water is an element.', exampleZh: '水是一种元素。', pos: 'n.', level: 'core' },

  // ==================== Day 10 (361-400) ====================
  { word: 'encourage', phonetic: '/ɪnˈkʌrɪdʒ/', meaning: 'v. 鼓励', example: 'She encouraged me to try.', exampleZh: '她鼓励我去尝试。', pos: 'v.', level: 'core' },
  { word: 'end', phonetic: '/end/', meaning: 'n. 结束 v. 结束', example: 'The movie ended at ten.', exampleZh: '电影十点结束。', pos: 'n.', level: 'core' },
  { word: 'energy', phonetic: '/ˈenədʒi/', meaning: 'n. 能量；精力', example: 'He has a lot of energy.', exampleZh: '他精力充沛。', pos: 'n.', level: 'core' },
  { word: 'engage', phonetic: '/ɪnˈɡeɪdʒ/', meaning: 'v. 参与；订婚', example: 'She engaged in the project.', exampleZh: '她参与了该项目。', pos: 'v.', level: 'core' },
  { word: 'engine', phonetic: '/ˈendʒɪn/', meaning: 'n. 发动机', example: 'The engine is broken.', exampleZh: '发动机坏了。', pos: 'n.', level: 'core' },
  { word: 'enjoy', phonetic: '/ɪnˈdʒɔɪ/', meaning: 'v. 享受', example: 'I enjoy reading books.', exampleZh: '我喜欢读书。', pos: 'v.', level: 'core' },
  { word: 'enough', phonetic: '/ɪˈnʌf/', meaning: 'adj. 足够的', example: 'I have enough money.', exampleZh: '我有足够的钱。', pos: 'adj.', level: 'core' },
  { word: 'ensure', phonetic: '/ɪnˈʃʊə/', meaning: 'v. 确保', example: 'Ensure the door is locked.', exampleZh: '确保门锁好了。', pos: 'v.', level: 'core' },
  { word: 'enter', phonetic: '/ˈentə/', meaning: 'v. 进入', example: 'He entered the room.', exampleZh: '他进了房间。', pos: 'v.', level: 'core' },
  { word: 'entire', phonetic: '/ɪnˈtaɪə/', meaning: 'adj. 整个的', example: 'I read the entire book.', exampleZh: '我读了整本书。', pos: 'adj.', level: 'core' },
  { word: 'environment', phonetic: '/ɪnˈvaɪrənmənt/', meaning: 'n. 环境', example: 'Protect the environment.', exampleZh: '保护环境。', pos: 'n.', level: 'core' },
  { word: 'equal', phonetic: '/ˈiːkwəl/', meaning: 'adj. 平等的', example: 'All people are equal.', exampleZh: '人人平等。', pos: 'adj.', level: 'core' },
  { word: 'equipment', phonetic: '/ɪˈkwɪpmənt/', meaning: 'n. 设备', example: 'We need new equipment.', exampleZh: '我们需要新设备。', pos: 'n.', level: 'core' },
  { word: 'error', phonetic: '/ˈerə/', meaning: 'n. 错误', example: 'I made an error.', exampleZh: '我犯了个错误。', pos: 'n.', level: 'core' },
  { word: 'escape', phonetic: '/ɪˈskeɪp/', meaning: 'v. 逃跑', example: 'The prisoner escaped.', exampleZh: '囚犯逃跑了。', pos: 'v.', level: 'core' },
  { word: 'especially', phonetic: '/ɪˈspeʃəli/', meaning: 'adv. 尤其', example: 'I especially like music.', exampleZh: '我特别喜欢音乐。', pos: 'adv.', level: 'core' },
  { word: 'establish', phonetic: '/ɪˈstæblɪʃ/', meaning: 'v. 建立', example: 'They established a school.', exampleZh: '他们建立了一所学校。', pos: 'v.', level: 'core' },
  { word: 'estimate', phonetic: '/ˈestɪmeɪt/', meaning: 'v. 估计 n. 估计', example: 'Estimate the total cost.', exampleZh: '估计总成本。', pos: 'v.', level: 'core' },
  { word: 'evaluate', phonetic: '/ɪˈvæljueɪt/', meaning: 'v. 评价', example: 'We need to evaluate the result.', exampleZh: '我们需要评估结果。', pos: 'v.', level: 'core' },
  { word: 'even', phonetic: '/ˈiːvn/', meaning: 'adv. 甚至', example: 'Even a child can do it.', exampleZh: '连孩子都能做。', pos: 'adv.', level: 'core' },
  { word: 'evening', phonetic: '/ˈiːvnɪŋ/', meaning: 'n. 傍晚', example: 'We met in the evening.', exampleZh: '我们傍晚见面。', pos: 'n.', level: 'core' },
  { word: 'event', phonetic: '/ɪˈvent/', meaning: 'n. 事件', example: 'It was a big event.', exampleZh: '这是个大事件。', pos: 'n.', level: 'core' },
  { word: 'ever', phonetic: '/ˈevə/', meaning: 'adv. 曾经', example: 'Have you ever been to Paris?', exampleZh: '你去过巴黎吗？', pos: 'adv.', level: 'core' },
  { word: 'every', phonetic: '/ˈevri/', meaning: 'adj. 每个', example: 'I study every day.', exampleZh: '我每天学习。', pos: 'adj.', level: 'core' },
  { word: 'evidence', phonetic: '/ˈevɪdəns/', meaning: 'n. 证据', example: 'There is no evidence.', exampleZh: '没有证据。', pos: 'n.', level: 'core' },
  { word: 'exact', phonetic: '/ɪɡˈzækt/', meaning: 'adj. 确切的', example: 'What is the exact time?', exampleZh: '确切时间是什么？', pos: 'adj.', level: 'core' },
  { word: 'examine', phonetic: '/ɪɡˈzæmɪn/', meaning: 'v. 检查', example: 'The doctor examined me.', exampleZh: '医生给我做了检查。', pos: 'v.', level: 'core' },
  { word: 'example', phonetic: '/ɪɡˈzɑːmpl/', meaning: 'n. 例子', example: 'Give me an example.', exampleZh: '给我一个例子。', pos: 'n.', level: 'core' },
  { word: 'excellent', phonetic: '/ˈeksələnt/', meaning: 'adj. 优秀的', example: 'She did an excellent job.', exampleZh: '她做得非常好。', pos: 'adj.', level: 'core' },
  { word: 'except', phonetic: '/ɪkˈsept/', meaning: 'prep. 除了', example: 'Everyone came except Tom.', exampleZh: '除了汤姆，所有人都来了。', pos: 'prep.', level: 'core' },
  { word: 'exchange', phonetic: '/ɪksˈtʃeɪndʒ/', meaning: 'v. 交换 n. 交换', example: 'They exchanged gifts.', exampleZh: '他们交换了礼物。', pos: 'v.', level: 'core' },
  { word: 'excited', phonetic: '/ɪkˈsaɪtɪd/', meaning: 'adj. 兴奋的', example: 'The children were excited.', exampleZh: '孩子们很兴奋。', pos: 'adj.', level: 'core' },
  { word: 'excuse', phonetic: '/ɪkˈskjuːz/', meaning: 'n. 借口 v. 原谅', example: 'What is your excuse?', exampleZh: '你的借口是什么？', pos: 'n.', level: 'core' },
  { word: 'exercise', phonetic: '/ˈeksəsaɪz/', meaning: 'n. 练习 v. 锻炼', example: 'Do exercise every day.', exampleZh: '每天锻炼。', pos: 'n.', level: 'core' }
];
// Total: 400 words, 10 days
